<?xml version="1.0" encoding="utf-8"?><Database Name="CardGame" Class="CardDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KEITH-LAPTOP;Initial Catalog=CardGame;Persist Security Info=True;User ID=cardgame" SettingsObjectName="CardGameConsoleTestApp.Properties.Settings" SettingsPropertyName="CardGameConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CardName" Member="CardNames">
    <Type Name="CardName">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LanguageId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Card_CardName" Member="Card" ThisKey="CardId" OtherKey="Id" Type="Card" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CardTrigger" Member="CardTriggers">
    <Type Name="CardTrigger">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TriggerType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MethodId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CardTrigger_CardTriggerParam" Member="CardTriggerParams" ThisKey="Id" OtherKey="CardTriggerId" Type="CardTriggerParam" />
      <Association Name="Method_CardTrigger" Member="Method" ThisKey="MethodId" OtherKey="Id" Type="Method" IsForeignKey="true" />
      <Association Name="Card_CardTrigger" Member="Card" ThisKey="CardId" OtherKey="Id" Type="Card" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CardTriggerParam" Member="CardTriggerParams">
    <Type Name="CardTriggerParam">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CardTriggerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParamName" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ParamValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="CardTrigger_CardTriggerParam" Member="CardTrigger" ThisKey="CardTriggerId" OtherKey="Id" Type="CardTrigger" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Method" Member="Methods">
    <Type Name="Method">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="VarChar(127) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(127) NOT NULL" CanBeNull="false" />
      <Association Name="Method_CardTrigger" Member="CardTriggers" ThisKey="Id" OtherKey="MethodId" Type="CardTrigger" />
    </Type>
  </Table>
  <Table Name="dbo.Card" Member="Cards">
    <Type Name="Card">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cost" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SubType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Attack" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Health" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="Card_CardName" Member="CardNames" ThisKey="Id" OtherKey="CardId" Type="CardName" />
      <Association Name="Card_CardTrigger" Member="CardTriggers" ThisKey="Id" OtherKey="CardId" Type="CardTrigger" />
      <Association Name="Card_DeckCard" Member="DeckCards" ThisKey="Id" OtherKey="CardId" Type="DeckCard" />
    </Type>
  </Table>
  <Table Name="dbo.DeckCard" Member="DeckCards">
    <Type Name="DeckCard">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeckId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CardId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Card_DeckCard" Member="Card" ThisKey="CardId" OtherKey="Id" Type="Card" IsForeignKey="true" />
      <Association Name="Deck_DeckCard" Member="Deck" ThisKey="DeckId" OtherKey="Id" Type="Deck" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Deck" Member="Decks">
    <Type Name="Deck">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Deck_DeckCard" Member="DeckCards" ThisKey="Id" OtherKey="DeckId" Type="DeckCard" />
    </Type>
  </Table>
</Database>